# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d911a945e62c210b3eadf09817b144a2382cfe72664885397553175abb9a66d1a75800a6833978d7428bf3a274e54fe0f17581b3af0864fe6decb04d9ab8ebe1

test:
  secret_key_base: c7471f6f8e5a675796e9216592cd5129d8bfd461399c2e186cd95d0de005da44a74f673001da5b06e7be52384870abf91fa3b1867a87b0eba8c800a6226b5e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
